---
- name: Install and Configure Consul Server
  hosts: consul-server
  remote_user: root
  roles:
    - common
    - server

- name: Activate Consul UI
  hosts: consul-server-ui
  remote_user: root
  roles:
    - ui
