---
- name: Set Hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Update Existing Packages
  community.general.zypper:
    name: '*'
    state: latest

- name: Install Common Packages
  community.general.zypper:
    name: "{{ common_packages }}"
    state: present
