- name: Template consul server config
  ansible.builtin.template:
    src: templates/ui-enabled.hcl.j2
    dest: "{{ consul_config_d_dir }}/ui-enabled.hcl"
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart consul

