---
- name: Copy TLS files to host
  ansible.builtin.copy:
    src: files/secrets/{{ item }}
    dest: "{{ consul_tls_dir }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - "{{ consul_ca }}"
    - "{{ consul_ca_key }}"
    - "{{ consul_server_cert }}"
    - "{{ consul_server_key }}"

- name: Copy gossip key to host
  ansible.builtin.copy:
    src: files/secrets/gossip.key
    dest: "{{ consul_config_dir }}"
    owner: root
    group: root
    mode: '0644'

- name: Template consul server config
  ansible.builtin.template:
    src: templates/consul.hcl.j2
    dest: "{{ consul_config_d_dir }}/consul.hcl"
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart consul

