---
- name: Copy TLS files to host
  ansible.builtin.copy:
    src: files/secrets/{{ item }}
    dest: "{{ consul_tls_dir }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ consul_tls_files }}"

- name: Copy gossip key to host
  ansible.builtin.copy:
    src: files/secrets/gossip.key
    dest: "{{ consul_config_dir }}"
    owner: root
    group: root
    mode: '0644'

- name: Template consul config
  ansible.builtin.template:
    src: templates/consul.hcl.j2
    dest: "{{ consul_config_d_dir }}/consul.hcl"
    owner: root
    group: root
    mode: '0644'

