---
- name: Unzip and Install Consul Server
  ansible.builtin.unarchive:
    src: "{{ consul_url }}"
    dest: "{{ consul_bin_dir }}"
    remote_src: yes

- name: Create Required Directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ consul_tls_dir }}"
    - "{{ consul_config_d_dir }}"
    - "{{ consul_data_dir }}"

- name: Write Unit File
  ansible.builtin.copy:
    src: files/consul.service
    dest: "{{ consul_service_file_dir }}/consul.service"
    owner: root
    group: root
    mode: 644
  notify:
    - daemon reload
    - restart consul

- name: Enable Unit File
  ansible.builtin.systemd:
    name: consul
    enabled: true

